"""rename model_name to ai_model

Revision ID: ea6b1fd27fc8
Revises: 5da009fe7ec0
Create Date: 2025-02-28 11:23:35.089009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea6b1fd27fc8'
down_revision: Union[str, None] = '5da009fe7ec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userconfig', sa.Column('ai_model', sa.String(length=50), nullable=False))
    op.drop_column('userconfig', 'model_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userconfig', sa.Column('model_name', sa.VARCHAR(length=50), nullable=False))
    op.drop_column('userconfig', 'ai_model')
    # ### end Alembic commands ###
